"""Markdown report generator for privy report.

Renders the structured sections dict produced by ``run_report()`` into a
single human-readable ``report.md`` file.  The output is valid GitHub-
Flavored Markdown and can be converted to HTML by ``render_html_report()``.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------

def render_markdown_report(
    sections: dict[str, Any],
    title: str,
    outdir: Path,
) -> Path:
    """Render a Markdown report from assembled sections.

    Args:
        sections: Structured data dict assembled by :func:`~privy.report.summary.run_report`.
        title:    Report title (used as the top-level H1 heading).
        outdir:   Output directory.

    Returns:
        Path to the written ``report.md``.
    """
    lines: list[str] = []

    _section_header(lines, title, sections.get("generated_at", ""))
    _section_run_summary(lines, sections)

    if sections.get("qc_rows") is not None:
        _section_qc(lines, sections)

    _section_top_hits(lines, sections)

    if sections.get("strictness_summary"):
        _section_strictness(lines, sections)

    if sections.get("region_rows") is not None:
        _section_regions(lines, sections)

    if sections.get("support_summary") is not None:
        _section_support(lines, sections)

    if sections.get("contradiction_rows"):
        _section_contradictions(lines, sections)

    _section_caveats(lines)

    out_path = outdir / "report.md"
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return out_path


# ---------------------------------------------------------------------------
# Section builders
# ---------------------------------------------------------------------------

def _section_header(lines: list[str], title: str, generated_at: str) -> None:
    lines.append(f"# {title}")
    lines.append("")
    if generated_at:
        lines.append(f"*Generated by Panex Privus on {generated_at}*")
        lines.append("")
    lines.append("---")
    lines.append("")


def _section_run_summary(lines: list[str], sections: dict[str, Any]) -> None:
    lines.append("## Run Summary")
    lines.append("")
    rows: list[dict[str, str]] = sections.get("run_summary_rows", [])
    if rows:
        lines.append(_md_table(
            ["Metric", "Value"],
            [[r.get("metric", ""), r.get("value", "")] for r in rows],
        ))
    else:
        lines.append("*No run summary available.*")
    lines.append("")
    lines.append("---")
    lines.append("")


def _section_qc(lines: list[str], sections: dict[str, Any]) -> None:
    lines.append("## Filtering and QC")
    lines.append("")
    qc_rows: list[dict[str, str]] = sections.get("qc_rows") or []
    if qc_rows:
        lines.append(_md_table(
            ["Metric", "Value", "Description"],
            [
                [r.get("metric", ""), r.get("value", ""), r.get("description", "")]
                for r in qc_rows
            ],
        ))
    else:
        lines.append("*No QC data available.*")
    lines.append("")
    lines.append("---")
    lines.append("")


def _section_top_hits(lines: list[str], sections: dict[str, Any]) -> None:
    ranked: list[dict[str, str]] = sections.get("ranked_hits") or []
    n_total: int = sections.get("n_total_hits", 0)
    top_n: int = sections.get("top_n", len(ranked))
    shown = len(ranked)

    lines.append(f"## Top {top_n} Hits")
    lines.append("")
    lines.append(
        f"Showing {shown} of {n_total} total hits, ranked by "
        "`final_score` (descending)."
    )
    lines.append("")

    if ranked:
        col_keys = [
            "locus_id", "contig", "start", "end", "variant_type",
            "strictness_class", "final_score",
        ]
        headers = ["rank", *col_keys]
        table_rows = [
            [str(i + 1)] + [r.get(k, "") for k in col_keys]
            for i, r in enumerate(ranked)
        ]
        lines.append(_md_table(headers, table_rows))
    else:
        lines.append("*No hits found.*")

    lines.append("")
    lines.append("---")
    lines.append("")


def _section_strictness(lines: list[str], sections: dict[str, Any]) -> None:
    lines.append("## Strictness Class Distribution")
    lines.append("")
    lines.append(
        "Every hit carries a `strictness_class` label indicating how complete "
        "the supporting data is.  See the README for class definitions."
    )
    lines.append("")
    rows: list[dict[str, Any]] = sections.get("strictness_summary") or []
    non_zero = [r for r in rows if r.get("n_loci", 0) > 0]
    if non_zero:
        lines.append(_md_table(
            ["Strictness Class", "Count", "% of Hits"],
            [
                [
                    r.get("strictness_class", ""),
                    str(r.get("n_loci", 0)),
                    f"{r.get('pct_hits', 0.0):.1f}%",
                ]
                for r in non_zero
            ],
        ))
    else:
        lines.append("*No hits to summarize.*")
    lines.append("")
    lines.append("---")
    lines.append("")


def _section_regions(lines: list[str], sections: dict[str, Any]) -> None:
    region_rows: list[dict[str, str]] = sections.get("region_rows") or []
    lines.append(f"## Candidate Regions ({len(region_rows)})")
    lines.append("")
    if region_rows:
        col_keys = [
            "region_id", "contig", "start", "end",
            "n_loci", "dominant_strictness_class", "final_score",
        ]
        display = region_rows[:50]
        lines.append(_md_table(
            col_keys,
            [[r.get(k, "") for k in col_keys] for r in display],
        ))
        if len(region_rows) > 50:
            lines.append("")
            lines.append(f"*…and {len(region_rows) - 50} more. See `regions.tsv`.*")
    else:
        lines.append("*No regions found.*")
    lines.append("")
    lines.append("---")
    lines.append("")


def _section_support(lines: list[str], sections: dict[str, Any]) -> None:
    rows: list[dict[str, Any]] = sections.get("support_summary") or []
    lines.append("## Source Support Summary")
    lines.append("")
    if rows:
        lines.append(_md_table(
            ["Source", "Evidence Class", "Count", "% of Source"],
            [
                [
                    r.get("source_type", ""),
                    r.get("evidence_class", ""),
                    str(r.get("n_records", 0)),
                    f"{r.get('pct_of_source', 0.0):.1f}%",
                ]
                for r in rows
            ],
        ))
    else:
        lines.append("*No evidence data available.*")
    lines.append("")
    lines.append("---")
    lines.append("")


def _section_contradictions(lines: list[str], sections: dict[str, Any]) -> None:
    rows: list[dict[str, str]] = sections.get("contradiction_rows") or []
    lines.append("## Contradiction Summary")
    lines.append("")
    if rows:
        lines.append(_md_table(
            ["Metric", "Value", "Description"],
            [
                [r.get("metric", ""), r.get("value", ""), r.get("description", "")]
                for r in rows
            ],
        ))
    else:
        lines.append("*No contradiction data available.*")
    lines.append("")
    lines.append("---")
    lines.append("")


def _section_caveats(lines: list[str]) -> None:
    lines.append("## Caveats and Limitations")
    lines.append("")
    lines.extend([
        "- `strict_complete` hits are the most reliable: all target and off-target "
        "samples had called genotypes at this position.",
        "- Hits with `strict_target_missing` or `strict_offtarget_missing` warrant "
        "closer inspection. Check `sample_support.tsv` to see which samples lacked "
        "calls and consider whether low coverage is the cause.",
        "- `final_score` is a transparent additive composite of discovery score, "
        "support score, and missingness penalty. Higher scores reflect data "
        "completeness, not biological certainty.",
        "- Off-target exclusion depends on the comprehensiveness of your off-target "
        "cohort. Alleles absent from an incomplete reference set may appear private "
        "even if they are shared more broadly.",
        "- For loci in repetitive or low-complexity regions, VCF quality scores may "
        "be less reliable. Use `--min-qual` to apply a QUAL filter in subsequent runs.",
    ])
    lines.append("")


# ---------------------------------------------------------------------------
# Markdown table utility
# ---------------------------------------------------------------------------

def _md_table(headers: list[str], rows: list[list[str]]) -> str:
    """Format data as a Markdown pipe table."""
    def _cell(v: Any) -> str:
        return str(v).replace("|", "&#124;").replace("\n", " ")

    header_line = "| " + " | ".join(_cell(h) for h in headers) + " |"
    sep_line = "| " + " | ".join("---" for _ in headers) + " |"
    row_lines = [
        "| " + " | ".join(_cell(c) for c in row) + " |"
        for row in rows
    ]
    return "\n".join([header_line, sep_line, *row_lines])
